<?php
/**
 * Free Shipping OffCanvas Content Customizer
 *
 * Adds Free Shipping content options for the OffCanvas Shipping Calculation.
 *
 * @package BlazeBlocksy
 * @since 1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Free Shipping OffCanvas Customizer Class
 *
 * Handles Free Shipping content including:
 * - Enable/disable toggle
 * - Rich text content
 * - Design options (Font, Border, Background)
 */
class BlazeBlocksy_Free_Shipping_Offcanvas_Customizer {

	/**
	 * Constructor
	 */
	public function __construct() {
		// Add options to WooCommerce > General section
		add_filter( 'blocksy_customizer_options:woocommerce:general:end', array( $this, 'add_customizer_options' ), 60 );

		// Generate dynamic CSS
		add_action( 'blocksy:global-dynamic-css:enqueue', array( $this, 'generate_dynamic_css' ), 10, 1 );

		// Add base CSS that applies CSS variables
		add_action( 'wp_head', array( $this, 'add_base_css' ), 99 );

		// Enqueue customizer preview script
		add_action( 'customize_preview_init', array( $this, 'enqueue_customizer_preview_script' ) );
	}

	/**
	 * Add base CSS that applies CSS variables to the element
	 *
	 * This CSS ensures the element uses the CSS variables generated by Blocksy.
	 *
	 * @return void
	 */
	public function add_base_css() {
		// Only output if feature is enabled
		if ( ! self::is_enabled() ) {
			return;
		}
		?>
		<style id="ct-free-shipping-offcanvas-base-css">
			.ct-free-shipping-offcanvas-content {
				/* Typography - uses Blocksy font variables */
				font-family: var(--theme-font-family, inherit);
				font-size: var(--theme-font-size, 14px);
				font-weight: var(--theme-font-weight, 400);
				font-style: var(--theme-font-style, normal);
				line-height: var(--theme-line-height, 1.5);
				letter-spacing: var(--theme-letter-spacing, 0);
				text-transform: var(--theme-text-transform, none);
				text-decoration: var(--theme-text-decoration, none);

				/* Color - uses direct color variable */
				color: var(--color, inherit);

				/* Border - uses Blocksy border variable generated by blocksy_output_border */
				border: var(--fs-offcanvas-border, 1px solid rgba(0, 0, 0, 0.1));

				/* Padding - default fallback, will be overridden by dynamic CSS */
				padding: var(--padding, 15px);

				/* Border Radius - default fallback, will be overridden by dynamic CSS */
				border-radius: var(--border-radius, 4px);

				/* Default margin */
				margin-bottom: 15px;
			}
		</style>
		<?php
	}

	/**
	 * Add customizer options to WooCommerce > General section
	 *
	 * @param array $options Existing Blocksy options array.
	 * @return array Modified options array with our custom options.
	 */
	public function add_customizer_options( $options ) {
		// Add panel for Free Shipping OffCanvas Content
		$options['free_shipping_offcanvas_panel'] = array(
			'label' => __( 'Off-Canvas Shipping Content', 'blaze-blocksy' ),
			'type' => 'ct-panel',
			'setting' => array( 'transport' => 'postMessage' ),
			'inner-options' => array(

				// Tab: Content
				'free_shipping_offcanvas_content_tab' => array(
					'title' => __( 'Content', 'blaze-blocksy' ),
					'type' => 'tab',
					'options' => array(

						// Enable/Disable Toggle
						'free_shipping_offcanvas_enabled' => array(
							'label' => __( 'Enable free shipping content on off-canvas shipping calculation', 'blaze-blocksy' ),
							'type' => 'ct-switch',
							'value' => 'no',
							'desc' => __( 'When enabled, displays custom free shipping content in the offcanvas shipping calculation panel.', 'blaze-blocksy' ),
							'setting' => array( 'transport' => 'postMessage' ),
						),

						// Conditional: Show rich text only when enabled
						blocksy_rand_md5() => array(
							'type' => 'ct-condition',
							'condition' => array( 'free_shipping_offcanvas_enabled' => 'yes' ),
							'options' => array(

								// Rich Text Content
								'free_shipping_offcanvas_content' => array(
									'label' => __( 'Content', 'blaze-blocksy' ),
									'type' => 'wp-editor',
									'value' => __( '<strong>🎉 Congratulations!</strong> You have qualified for free shipping!', 'blaze-blocksy' ),
									'desc' => __( 'Enter the content to display when free shipping is available. HTML is supported.', 'blaze-blocksy' ),
									'setting' => array( 'transport' => 'postMessage' ),
									'quicktags' => true,
									'mediaButtons' => false,
								),

							),
						),

					),
				),

				// Tab: Design
				'free_shipping_offcanvas_design_tab' => array(
					'title' => __( 'Design', 'blaze-blocksy' ),
					'type' => 'tab',
					'options' => array(

						// Conditional: Show design options only when enabled
						blocksy_rand_md5() => array(
							'type' => 'ct-condition',
							'condition' => array( 'free_shipping_offcanvas_enabled' => 'yes' ),
							'options' => array(

								// Typography Section Title
								blocksy_rand_md5() => array(
									'type' => 'ct-title',
									'label' => __( 'Typography', 'blaze-blocksy' ),
								),

								// Font Configuration
								'free_shipping_offcanvas_font' => array(
									'type' => 'ct-typography',
									'label' => __( 'Font', 'blaze-blocksy' ),
									'value' => blocksy_typography_default_values(
										array(
											'size' => '14px',
											'variation' => 'n4',
											'line-height' => '1.5',
										)
									),
									'setting' => array( 'transport' => 'postMessage' ),
								),

								// Font Color
								'free_shipping_offcanvas_font_color' => array(
									'label' => __( 'Font Color', 'blaze-blocksy' ),
									'type' => 'ct-color-picker',
									'design' => 'inline',
									'setting' => array( 'transport' => 'postMessage' ),
									'value' => array(
										'default' => array(
											'color' => Blocksy_Css_Injector::get_skip_rule_keyword( 'DEFAULT' ),
										),
									),
									'pickers' => array(
										array(
											'title' => __( 'Initial', 'blaze-blocksy' ),
											'id' => 'default',
											'inherit' => 'var(--theme-text-color)',
										),
									),
								),

								// Border Section Title
								blocksy_rand_md5() => array(
									'type' => 'ct-title',
									'label' => __( 'Border', 'blaze-blocksy' ),
									'divider' => 'top:full',
								),

								// Border Configuration
								'free_shipping_offcanvas_border' => array(
									'label' => __( 'Border', 'blaze-blocksy' ),
									'type' => 'ct-border',
									'design' => 'block',
									'divider' => 'top',
									'value' => array(
										'width' => 1,
										'style' => 'solid',
										'color' => array(
											'color' => 'rgba(0, 0, 0, 0.1)',
										),
									),
									'setting' => array( 'transport' => 'postMessage' ),
								),

								// Border Radius
								'free_shipping_offcanvas_border_radius' => array(
									'label' => __( 'Border Radius', 'blaze-blocksy' ),
									'type' => 'ct-spacing',
									'value' => blocksy_spacing_value(
										array(
											'linked' => true,
											'top' => '4px',
											'left' => '4px',
											'right' => '4px',
											'bottom' => '4px',
										)
									),
									'responsive' => true,
									'setting' => array( 'transport' => 'postMessage' ),
								),

								// Background Section Title
								blocksy_rand_md5() => array(
									'type' => 'ct-title',
									'label' => __( 'Background', 'blaze-blocksy' ),
									'divider' => 'top:full',
								),

								// Background Configuration
								'free_shipping_offcanvas_background' => array(
									'label' => __( 'Background', 'blaze-blocksy' ),
									'type' => 'ct-background',
									'design' => 'block:right',
									'responsive' => true,
									'sync' => 'live',
									'value' => blocksy_background_default_value(
										array(
											'backgroundColor' => array(
												'default' => array(
													'color' => '#f0f9f0',
												),
											),
										)
									),
									'setting' => array( 'transport' => 'postMessage' ),
								),

								// Padding
								'free_shipping_offcanvas_padding' => array(
									'label' => __( 'Padding', 'blaze-blocksy' ),
									'type' => 'ct-spacing',
									'value' => blocksy_spacing_value(
										array(
											'linked' => true,
											'top' => '15px',
											'left' => '15px',
											'right' => '15px',
											'bottom' => '15px',
										)
									),
									'responsive' => true,
									'setting' => array( 'transport' => 'postMessage' ),
								),

							),
						),

					),
				),

			),
		);

		return $options;
	}

	/**
	 * Enqueue customizer preview script for instant live preview
	 *
	 * @return void
	 */
	public function enqueue_customizer_preview_script() {
		$js_file = get_stylesheet_directory() . '/assets/js/customizer-preview-free-shipping-offcanvas.js';
		if ( file_exists( $js_file ) ) {
			wp_enqueue_script(
				'blaze-blocksy-free-shipping-offcanvas-customizer-preview',
				get_stylesheet_directory_uri() . '/assets/js/customizer-preview-free-shipping-offcanvas.js',
				array( 'jquery', 'customize-preview' ),
				filemtime( $js_file ),
				true
			);
		}
	}

	/**
	 * Generate dynamic CSS for Free Shipping OffCanvas
	 *
	 * Uses CSS custom properties for proper live preview and persistence.
	 *
	 * @param array $args CSS generation arguments from Blocksy.
	 * @return void
	 */
	public function generate_dynamic_css( $args ) {
		$css = $args['css'];
		$tablet_css = $args['tablet_css'];
		$mobile_css = $args['mobile_css'];

		// Check if feature is enabled
		$is_enabled = blocksy_get_theme_mod( 'free_shipping_offcanvas_enabled', 'no' );

		if ( 'yes' !== $is_enabled ) {
			return;
		}

		$selector = '.ct-free-shipping-offcanvas-content';

		// Typography
		blocksy_output_font_css(
			array(
				'font_value' => blocksy_get_theme_mod(
					'free_shipping_offcanvas_font',
					blocksy_typography_default_values(
						array(
							'size' => '14px',
							'variation' => 'n4',
							'line-height' => '1.5',
						)
					)
				),
				'css' => $css,
				'tablet_css' => $tablet_css,
				'mobile_css' => $mobile_css,
				'selector' => $selector,
			)
		);

		// Font Color - using 'color' variable for direct output
		blocksy_output_colors(
			array(
				'value' => blocksy_get_theme_mod( 'free_shipping_offcanvas_font_color' ),
				'default' => array(
					'default' => array( 'color' => Blocksy_Css_Injector::get_skip_rule_keyword( 'DEFAULT' ) ),
				),
				'css' => $css,
				'variables' => array(
					'default' => array(
						'selector' => $selector,
						'variable' => 'color',
					),
				),
			)
		);

		// Background
		blocksy_output_background_css(
			array(
				'selector' => $selector,
				'css' => $css,
				'tablet_css' => $tablet_css,
				'mobile_css' => $mobile_css,
				'value' => blocksy_get_theme_mod(
					'free_shipping_offcanvas_background',
					blocksy_background_default_value(
						array(
							'backgroundColor' => array(
								'default' => array(
									'color' => '#f0f9f0',
								),
							),
						)
					)
				),
				'responsive' => true,
			)
		);

		// Border - using blocksy_output_border for proper responsive support
		blocksy_output_border(
			array(
				'css' => $css,
				'tablet_css' => $tablet_css,
				'mobile_css' => $mobile_css,
				'selector' => $selector,
				'variableName' => 'fs-offcanvas-border',
				'value' => blocksy_get_theme_mod(
					'free_shipping_offcanvas_border',
					array(
						'width' => 1,
						'style' => 'solid',
						'color' => array(
							'color' => 'rgba(0, 0, 0, 0.1)',
						),
					)
				),
				'default' => array(
					'width' => 1,
					'style' => 'solid',
					'color' => array(
						'color' => 'rgba(0, 0, 0, 0.1)',
					),
				),
			)
		);

		// Border Radius - using blocksy_output_spacing for proper responsive support
		blocksy_output_spacing(
			array(
				'css' => $css,
				'tablet_css' => $tablet_css,
				'mobile_css' => $mobile_css,
				'selector' => $selector,
				'property' => 'border-radius',
				'value' => blocksy_get_theme_mod(
					'free_shipping_offcanvas_border_radius',
					blocksy_spacing_value(
						array(
							'linked' => true,
							'top' => '4px',
							'left' => '4px',
							'right' => '4px',
							'bottom' => '4px',
						)
					)
				),
			)
		);

		// Padding - using blocksy_output_spacing for proper responsive support
		blocksy_output_spacing(
			array(
				'css' => $css,
				'tablet_css' => $tablet_css,
				'mobile_css' => $mobile_css,
				'selector' => $selector,
				'property' => 'padding',
				'value' => blocksy_get_theme_mod(
					'free_shipping_offcanvas_padding',
					blocksy_spacing_value(
						array(
							'linked' => true,
							'top' => '15px',
							'left' => '15px',
							'right' => '15px',
							'bottom' => '15px',
						)
					)
				),
			)
		);
	}

	/**
	 * Check if free shipping offcanvas content is enabled
	 *
	 * @return bool True if enabled, false otherwise.
	 */
	public static function is_enabled() {
		$value = get_theme_mod( 'free_shipping_offcanvas_enabled', 'no' );
		return ( 'yes' === $value );
	}

	/**
	 * Get the free shipping offcanvas content
	 *
	 * @return string The content HTML.
	 */
	public static function get_content() {
		return get_theme_mod(
			'free_shipping_offcanvas_content',
			__( '<strong>🎉 Congratulations!</strong> You have qualified for free shipping!', 'blaze-blocksy' )
		);
	}

	/**
	 * Get allowed HTML tags including SVG elements
	 *
	 * @return array Allowed HTML tags for wp_kses.
	 */
	public static function get_allowed_html_tags() {
		// Start with post allowed tags
		$allowed_tags = wp_kses_allowed_html( 'post' );

		// Add SVG elements
		$svg_tags = array(
			'svg' => array(
				'class' => true,
				'aria-hidden' => true,
				'aria-labelledby' => true,
				'role' => true,
				'xmlns' => true,
				'width' => true,
				'height' => true,
				'viewbox' => true,
				'fill' => true,
				'stroke' => true,
				'stroke-width' => true,
				'stroke-linecap' => true,
				'stroke-linejoin' => true,
				'style' => true,
				'id' => true,
			),
			'g' => array(
				'fill' => true,
				'stroke' => true,
				'stroke-width' => true,
				'transform' => true,
				'id' => true,
				'class' => true,
			),
			'title' => array(
				'title' => true,
			),
			'path' => array(
				'd' => true,
				'fill' => true,
				'stroke' => true,
				'stroke-width' => true,
				'stroke-linecap' => true,
				'stroke-linejoin' => true,
				'transform' => true,
				'id' => true,
				'class' => true,
			),
			'circle' => array(
				'cx' => true,
				'cy' => true,
				'r' => true,
				'fill' => true,
				'stroke' => true,
				'stroke-width' => true,
				'id' => true,
				'class' => true,
			),
			'rect' => array(
				'x' => true,
				'y' => true,
				'width' => true,
				'height' => true,
				'rx' => true,
				'ry' => true,
				'fill' => true,
				'stroke' => true,
				'stroke-width' => true,
				'id' => true,
				'class' => true,
			),
			'line' => array(
				'x1' => true,
				'y1' => true,
				'x2' => true,
				'y2' => true,
				'stroke' => true,
				'stroke-width' => true,
				'id' => true,
				'class' => true,
			),
			'polygon' => array(
				'points' => true,
				'fill' => true,
				'stroke' => true,
				'stroke-width' => true,
				'id' => true,
				'class' => true,
			),
			'polyline' => array(
				'points' => true,
				'fill' => true,
				'stroke' => true,
				'stroke-width' => true,
				'id' => true,
				'class' => true,
			),
			'ellipse' => array(
				'cx' => true,
				'cy' => true,
				'rx' => true,
				'ry' => true,
				'fill' => true,
				'stroke' => true,
				'stroke-width' => true,
				'id' => true,
				'class' => true,
			),
			'text' => array(
				'x' => true,
				'y' => true,
				'dx' => true,
				'dy' => true,
				'fill' => true,
				'font-size' => true,
				'font-family' => true,
				'text-anchor' => true,
				'id' => true,
				'class' => true,
			),
			'defs' => array(
				'id' => true,
			),
			'use' => array(
				'href' => true,
				'xlink:href' => true,
				'x' => true,
				'y' => true,
				'width' => true,
				'height' => true,
				'id' => true,
				'class' => true,
			),
			'symbol' => array(
				'id' => true,
				'viewbox' => true,
				'class' => true,
			),
		);

		return array_merge( $allowed_tags, $svg_tags );
	}

	/**
	 * Render the free shipping offcanvas content
	 *
	 * @return void
	 */
	public static function render() {
		$is_enabled = self::is_enabled();
		$is_customizer_preview = is_customize_preview();

		// In customizer preview, always render the element (hidden if disabled)
		// This allows JavaScript live preview to work properly
		if ( ! $is_enabled && ! $is_customizer_preview ) {
			return;
		}

		$content = self::get_content();

		// In customizer preview, show placeholder if content is empty
		if ( empty( $content ) && ! $is_customizer_preview ) {
			return;
		}

		// Set display style based on enabled state
		$style = $is_enabled ? '' : ' style="display: none;"';

		echo '<div class="ct-free-shipping-offcanvas-content"' . $style . '>';
		echo wp_kses( $content, self::get_allowed_html_tags() );
		echo '</div>';
	}
}

// Initialize the customizer integration
new BlazeBlocksy_Free_Shipping_Offcanvas_Customizer();

/**
 * Helper function to check if free shipping offcanvas content is enabled
 *
 * @return bool True if enabled, false otherwise.
 */
function blaze_blocksy_is_free_shipping_offcanvas_enabled() {
	return BlazeBlocksy_Free_Shipping_Offcanvas_Customizer::is_enabled();
}

/**
 * Helper function to get the free shipping offcanvas content
 *
 * @return string The content HTML.
 */
function blaze_blocksy_get_free_shipping_offcanvas_content() {
	return BlazeBlocksy_Free_Shipping_Offcanvas_Customizer::get_content();
}

/**
 * Helper function to render the free shipping offcanvas content
 *
 * @return void
 */
function blaze_blocksy_render_free_shipping_offcanvas_content() {
	BlazeBlocksy_Free_Shipping_Offcanvas_Customizer::render();
}
