<?php
/**
 * Product Stock Customizer
 *
 * Adds Product Stock element in Product Elements with design options.
 *
 * @package BlazeBlocksy
 * @since 1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Product Stock Customizer Class
 *
 * Handles Product Stock element including:
 * - Product Stock element for Product Elements
 * - Design options (Font, Colors for In Stock, Out of Stock, On Backorder)
 *
 * NOTE: Live preview requires JavaScript sync configuration in parent theme.
 * Since we're in child theme, we use blocksy_sync_whole_page() for selective refresh.
 * This means preview updates after a brief reload of the element area.
 */
class BlazeBlocksy_Product_Stock_Customizer {

	/**
	 * Constructor
	 */
	public function __construct() {
		// Register Product Stock element in Product Elements
		add_filter( 'blocksy_woo_single_options_layers:defaults', array( $this, 'register_layer_defaults' ) );
		add_filter( 'blocksy_woo_single_options_layers:extra', array( $this, 'register_layer_options' ) );
		add_action( 'blocksy:woocommerce:product:custom:layer', array( $this, 'render_layer' ) );

		// Add Design Options to Design Tab
		add_filter( 'blocksy:options:single_product:elements:design_tab:end', array( $this, 'register_design_options' ) );

		// Generate dynamic CSS
		add_action( 'blocksy:global-dynamic-css:enqueue', array( $this, 'generate_dynamic_css' ), 10, 1 );

		// Add base CSS that uses the CSS variables
		add_action( 'wp_head', array( $this, 'add_base_css' ), 99 );

		// Enqueue customizer preview script for instant live preview
		add_action( 'customize_preview_init', array( $this, 'enqueue_customizer_preview_script' ) );
	}

	/**
	 * Enqueue customizer preview script for instant live preview
	 *
	 * @return void
	 */
	public function enqueue_customizer_preview_script() {
		wp_enqueue_script(
			'blaze-blocksy-product-stock-customizer-preview',
			get_stylesheet_directory_uri() . '/assets/js/customizer-preview-product-stock.js',
			array( 'jquery', 'customize-preview' ),
			filemtime( get_stylesheet_directory() . '/assets/js/customizer-preview-product-stock.js' ),
			true
		);
	}

	/**
	 * Add base CSS that applies CSS variables to the element
	 *
	 * This CSS ensures the element uses the CSS variables generated by Blocksy.
	 * Variables like --color, --theme-font-size, etc. are set by blocksy_output_colors()
	 * and blocksy_output_font_css(), but they need to be applied to actual CSS properties.
	 *
	 * @return void
	 */
	public function add_base_css() {
		if ( ! function_exists( 'is_product' ) || ! is_product() ) {
			return;
		}
		?>
		<style id="ct-product-stock-base-css">
			.ct-product-stock-element {
				font-family: var(--theme-font-family, inherit);
				font-size: var(--theme-font-size, 14px);
				font-weight: var(--theme-font-weight, 400);
				font-style: var(--theme-font-style, normal);
				line-height: var(--theme-line-height, 1.4);
				letter-spacing: var(--theme-letter-spacing, 0);
				text-transform: var(--theme-text-transform, none);
				text-decoration: var(--theme-text-decoration, none);
				color: var(--color, inherit);
			}
		</style>
		<?php
	}


	/**
	 * Add layer to default layout
	 *
	 * @param array $defaults Default layers.
	 * @return array
	 */
	public function register_layer_defaults( $defaults ) {
		$defaults[] = array(
			'id' => 'product_stock_element',
			'enabled' => false,
		);
		return $defaults;
	}

	/**
	 * Register layer options for Product Stock element
	 *
	 * @param array $options Existing options.
	 * @return array
	 */
	public function register_layer_options( $options ) {
		$options['product_stock_element'] = array(
			'label' => __( 'Product Stock', 'blaze-blocksy' ),
			'options' => array(
				// Bottom Spacing
				'spacing' => array(
					'label' => __( 'Bottom Spacing', 'blaze-blocksy' ),
					'type' => 'ct-slider',
					'min' => 0,
					'max' => 100,
					'value' => 20,
					'responsive' => true,
					'sync' => array( 'id' => 'woo_single_layout_skip' ),
				),
			),
		);

		return $options;
	}

	/**
	 * Register design options in Design Tab
	 *
	 * @param array $options Existing options.
	 * @return array
	 */
	public function register_design_options( $options ) {
		$options[blocksy_rand_md5()] = array(
			'type' => 'ct-condition',
			'condition' => array( 'woo_single_layout:array-ids:product_stock_element:enabled' => '!no' ),
			'computed_fields' => array( 'woo_single_layout' ),
			'options' => array(

				// Section Divider
				blocksy_rand_md5() => array(
					'type' => 'ct-divider',
				),

				// Section Title
				blocksy_rand_md5() => array(
					'type' => 'ct-title',
					'label' => __( 'Product Stock', 'blaze-blocksy' ),
				),

				// Typography
				'productStockFont' => array(
					'type' => 'ct-typography',
					'label' => __( 'Font', 'blaze-blocksy' ),
					'value' => blocksy_typography_default_values(
						array(
							'size' => '14px',
							'variation' => 'n4',
						)
					),
					'setting' => array( 'transport' => 'postMessage' ),
				),

				// In Stock Color
				'productStockInStockColor' => array(
					'label' => __( 'In Stock Color', 'blaze-blocksy' ),
					'type' => 'ct-color-picker',
					'design' => 'inline',
					'setting' => array( 'transport' => 'postMessage' ),
					'value' => array(
						'default' => array(
							'color' => '#46a529',
						),
					),
					'pickers' => array(
						array(
							'title' => __( 'Color', 'blaze-blocksy' ),
							'id' => 'default',
						),
					),
				),

				// Out of Stock Color
				'productStockOutOfStockColor' => array(
					'label' => __( 'Out of Stock Color', 'blaze-blocksy' ),
					'type' => 'ct-color-picker',
					'design' => 'inline',
					'setting' => array( 'transport' => 'postMessage' ),
					'value' => array(
						'default' => array(
							'color' => '#dc3545',
						),
					),
					'pickers' => array(
						array(
							'title' => __( 'Color', 'blaze-blocksy' ),
							'id' => 'default',
						),
					),
				),

				// On Backorder Color
				'productStockOnBackorderColor' => array(
					'label' => __( 'On Backorder Color', 'blaze-blocksy' ),
					'type' => 'ct-color-picker',
					'design' => 'inline',
					'setting' => array( 'transport' => 'postMessage' ),
					'value' => array(
						'default' => array(
							'color' => '#f0ad4e',
						),
					),
					'pickers' => array(
						array(
							'title' => __( 'Color', 'blaze-blocksy' ),
							'id' => 'default',
						),
					),
				),
			),
		);

		return $options;
	}

	/**
	 * Render the Product Stock layer
	 *
	 * @param array $layer Layer configuration.
	 * @return void
	 */
	public function render_layer( $layer ) {
		if ( 'product_stock_element' !== $layer['id'] ) {
			return;
		}

		global $product;

		if ( ! $product ) {
			return;
		}

		$availability = $product->get_availability();
		$stock_status = $product->get_stock_status();

		if ( empty( $availability['availability'] ) ) {
			return;
		}

		$status_class = 'in-stock';
		if ( 'outofstock' === $stock_status ) {
			$status_class = 'out-of-stock';
		} elseif ( 'onbackorder' === $stock_status ) {
			$status_class = 'on-backorder';
		}

		echo '<div class="ct-product-stock-element ct-product-stock-' . esc_attr( $status_class ) . '" data-element="product_stock_element">';
		echo '<span class="stock ' . esc_attr( $availability['class'] ) . '">' . wp_kses_post( $availability['availability'] ) . '</span>';
		echo '</div>';
	}

	/**
	 * Generate dynamic CSS for Product Stock
	 *
	 * Uses blocksy_output_colors() with 'color' property for direct CSS output.
	 * This ensures colors work immediately without JavaScript sync.
	 *
	 * @param array $args CSS generation arguments from Blocksy.
	 * @return void
	 */
	public function generate_dynamic_css( $args ) {
		$css = $args['css'];
		$tablet_css = $args['tablet_css'];
		$mobile_css = $args['mobile_css'];

		// Check if layer is enabled and get layer config
		$layout = blocksy_get_theme_mod( 'woo_single_layout', array() );
		$layer_config = null;

		foreach ( $layout as $layer ) {
			if ( isset( $layer['id'] ) && 'product_stock_element' === $layer['id'] && ! empty( $layer['enabled'] ) ) {
				$layer_config = $layer;
				break;
			}
		}

		if ( ! $layer_config ) {
			return;
		}

		// Output spacing CSS
		$spacing = blocksy_akg( 'spacing', $layer_config, 20 );
		blocksy_output_responsive(
			array(
				'css' => $css,
				'tablet_css' => $tablet_css,
				'mobile_css' => $mobile_css,
				'selector' => '.entry-summary-items > .ct-product-stock-element',
				'variableName' => 'product-element-spacing',
				'value' => $spacing,
				'unit' => 'px',
			)
		);

		// Typography
		blocksy_output_font_css(
			array(
				'font_value' => blocksy_get_theme_mod(
					'productStockFont',
					blocksy_typography_default_values(
						array(
							'size' => '14px',
							'variation' => 'n4',
						)
					)
				),
				'css' => $css,
				'tablet_css' => $tablet_css,
				'mobile_css' => $mobile_css,
				'selector' => '.ct-product-stock-element',
			)
		);

		// In Stock Color - using 'color' property for direct output
		blocksy_output_colors(
			array(
				'value' => blocksy_get_theme_mod( 'productStockInStockColor' ),
				'default' => array(
					'default' => array( 'color' => '#46a529' ),
				),
				'css' => $css,
				'variables' => array(
					'default' => array(
						'selector' => '.ct-product-stock-element.ct-product-stock-in-stock',
						'variable' => 'color',
					),
				),
			)
		);

		// Out of Stock Color - using 'color' property for direct output
		blocksy_output_colors(
			array(
				'value' => blocksy_get_theme_mod( 'productStockOutOfStockColor' ),
				'default' => array(
					'default' => array( 'color' => '#dc3545' ),
				),
				'css' => $css,
				'variables' => array(
					'default' => array(
						'selector' => '.ct-product-stock-element.ct-product-stock-out-of-stock',
						'variable' => 'color',
					),
				),
			)
		);

		// On Backorder Color - using 'color' property for direct output
		blocksy_output_colors(
			array(
				'value' => blocksy_get_theme_mod( 'productStockOnBackorderColor' ),
				'default' => array(
					'default' => array( 'color' => '#f0ad4e' ),
				),
				'css' => $css,
				'variables' => array(
					'default' => array(
						'selector' => '.ct-product-stock-element.ct-product-stock-on-backorder',
						'variable' => 'color',
					),
				),
			)
		);
	}
}

// Initialize
new BlazeBlocksy_Product_Stock_Customizer();
